# Generated by Django 4.2.4 on 2023-09-19 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('payroll_number', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.PositiveIntegerField()),
                ('min_gender', models.BooleanField()),
                ('min_general', models.BooleanField()),
                ('role', models.IntegerField()),
                ('status', models.BooleanField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scaItescaApp.area')),
            ],
        ),
    ]
